### ISSUE TITLE
Unicode error when trying to post

### ISSUE THREAD

**Issue by don-philipe** [dialelo/turses#202]
Hi,

when posting I get the error `[ERROR] => Tweet not send` in the bottom left of the UI, the following error appears in the log file and nothing will be posted (regardless of the characters I'm writing):

`ERROR:root:'ascii' codec can't encode character u'\xe4' in position 0: ordinal not in range(128)
Traceback (most recent call last):`
`File "/usr/lib/python2.7/site-packages/turses/meta.py", line 31, in wrapper
    result = func(self, *args, **kwargs)`
`File "/usr/lib/python2.7/site-packages/turses/api/base.py", line 308, in update
    self._api.update(text)`
`File "/usr/lib/python2.7/site-packages/turses/api/backends.py", line 296, in update
    self._api.update_status(text)`
`File "/usr/lib/python2.7/site-packages/tweepy/api.py", line 184, in update_status
    post_data["media_ids"] = list_to_csv(media_ids)`
`File "/usr/lib/python2.7/site-packages/tweepy/utils.py", line 58, in list_to_csv
    return ','.join([str(i) for i in item_list])`
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 0: ordinal not in range(128)`

I'm on archlinux and using the latest turses version from the AUR together with python2-tweepy 3.3.0-2. As terminal emulator I'm using urxvt.

**Comment by mikos** [comment]
+1

**Comment by don-philipe** [comment]
Hm, this seems to be a tweepy issue.
Found this today: https://github.com/tweepy/tweepy/issues/580

**Comment by cyphar** [comment]
This is why Guido invented py3k :P. In all seriousness, why isn't turses python3-compatible?

**Comment by dialelo** [comment]
It is compatible with Python 3 as of the last release.

**Comment by cyphar** [comment]
I beg to differ:

```
% pip3 show turses
---
Metadata-Version: 2.0
Name: turses
Version: 0.3.1
Summary: A Twitter client for the console.
Home-page: http://github.com/alejandrogomez/turses
Author: Alejandro Gómez
Author-email: alejandro@dialelo.com
License: UNKNOWN
Location: /usr/local/lib/python3.4/site-packages
Requires: urwid, tweepy, future
% turses
Traceback (most recent call last):
  File "/usr/local/bin/turses", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/turses/cli.py", line 146, in main
    configuration.load()
  File "/usr/local/lib/python3.4/site-packages/turses/config.py", line 504, in load
    self._init_config()
  File "/usr/local/lib/python3.4/site-packages/turses/config.py", line 513, in _init_config
    self.parse_config_file(self.config_file)
  File "/usr/local/lib/python3.4/site-packages/turses/config.py", line 716, in parse_config_file
    self._parse_styles(conf)
  File "/usr/local/lib/python3.4/site-packages/turses/config.py", line 760, in _parse_styles
    conf.get(SECTION_STYLES, style), 'utf-8')
TypeError: decoding str is not supported
%
```

**Comment by dialelo** [comment]
I'd be happy to accept a patch fixing it then.
