### ISSUE TITLE
400 Status Code when Posting

### ISSUE THREAD

**Issue by cyphar** [dialelo/turses#208]
I cannot post any tweets, and the following error is in the traceback:

```
DEBUG:requests.packages.urllib3.connectionpool:"POST /1.1/statuses/update.json HTTP/1.1" 400 68
ERROR:root:Twitter error response: status code = 400
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/turses-0.3.1-py3.4.egg/turses/meta.py", line 35, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/turses-0.3.1-py3.4.egg/turses/api/base.py", line 311, in update
    self._api.update(text)
  File "/usr/local/lib/python3.4/site-packages/turses-0.3.1-py3.4.egg/turses/api/backends.py", line 296, in update
    self._api.update_status(text)
  File "/usr/local/lib/python3.4/site-packages/tweepy/api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tweepy/binder.py", line 239, in _call
    return method.execute()
  File "/usr/local/lib/python3.4/site-packages/tweepy/binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: Twitter error response: status code = 400
```

Is this a tweepy-specific issue, or are we doing something weird here?

**Comment by dialelo** [comment]
This should be a Tweepy problem.

**Comment by cyphar** [comment]
tweepy/tweepy#554 says that the Tweepy API had a breaking change such that `self._api.update_status(text)` is no longer valid, you have to explicitly specify the `kwargs`. However, there is a PR to fix it (tweepy/tweepy#578), but I feel like waiting for them to fix it is a pain. We should either revert our requirements to `tweepy==3.1.0` until they fix it, or change it so that it uses `self._api.update_status(status=text)`.

**Comment by dialelo** [comment]
Let's revert to the `tweepy` version we know it works then, thanks for your time!
