### ISSUE TITLE
Crashes at start; "TypeError: decoding str is not supported"

### ISSUE THREAD

**Issue by Hund** [dialelo/turses#210]
I tried installing Turses from  AUR (I'm running Arch Linux), but it didnt want to compile it. So I took the easy way and installed Turses via Pythons package manager instead. But when I try to start Turses it crashes leaving this output:

```
Traceback (most recent call last):
  File "/usr/bin/turses", line 9, in <module>
    load_entry_point('turses==0.3.1', 'console_scripts', 'turses')()
  File "/usr/lib/python3.4/site-packages/turses/cli.py", line 146, in main
    configuration.load()
  File "/usr/lib/python3.4/site-packages/turses/config.py", line 504, in load
    self._init_config()
  File "/usr/lib/python3.4/site-packages/turses/config.py", line 513, in _init_config
    self.parse_config_file(self.config_file)
  File "/usr/lib/python3.4/site-packages/turses/config.py", line 716, in parse_config_file
    self._parse_styles(conf)
  File "/usr/lib/python3.4/site-packages/turses/config.py", line 760, in _parse_styles
    conf.get(SECTION_STYLES, style), 'utf-8')
TypeError: decoding str is not supported
```

I really dont know what to do here?

**Comment by alfrex** [comment]
Hi, I installed Turses from AUR (on Manjaro) and compiled it correctly (you used yaourt?, have installed all dependencies of it?). Anyway, try changing the python env version in the first line of the script:
sudo nano /usr/bin/turses

#!/usr/bin/python2

by

#!/usr/bin/python

or vice versa

**Comment by cyphar** [comment]
@Hund this bug was fixed by #207. It's because the conversion from `python2` to `python3` included a bug. It doesn't seem that the turses release has been updated since that PR was merged.

**Comment by Hund** [comment]
@cyphar Thanks! Now I just have to figure out why I cant tweet.

**Comment by cyphar** [comment]
@Hund that was also fixed in #208. :P

**Comment by shaggytwodope** [comment]
@Hund Maintainer of the aur package here, basicly aside from stuff @cyphar mentioned. There was some updates to other stuff recently that caused some funky stuff. That all side tho, turses SHOULD be fully working. I've changed the source for tweepy (using git atm) it includes the latest fixes. So update turses as you do with all aur packages. And everything should be working great. https://twitter.com/twodopeshaggy/status/643947316953526272

Not sure the python3 release is ready enough to switch the package over yet btw, anyone confirm it's stability?

**Comment by cyphar** [comment]
@shaggytwodope Well, the most recent release had the (broken) Python 3 port. So it's more stable now than it was when released. :P

**Comment by Hund** [comment]
@shaggytwodope Sweet! I updated Turses and sending tweets works again. :)
