### ISSUE TITLE
Package Six too recent

### ISSUE THREAD

**Issue by dmaglio** [dialelo/turses#218]
I have six v.1.10.0 installed but turses don't work:
```
Traceback (most recent call last):
  File "/usr/bin/turses", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six==1.7.3' distribution was not found and is required by tweepy
```

**Comment by dialelo** [comment]
It depends on another version of `six` as shown in the error message: `six==1.7.3`. I'm not mantaining turses anymore by the way.
