### ISSUE TITLE
ERROR => Tweet not send

### ISSUE THREAD

**Issue by Chinggis6** [dialelo/turses#220]
Thank you, it is really an awesome project but:

I could authorize with the token, could start turses, and receive everything, but I cannot send anything from it. Tweepy's version is 3.3.0. When I upgrade it to 3.5 it doesn't *even* start. I installed the program using `pip install`. It works only for reading, cannot send tweets, reply, retweet etc. I am on Fedora 25 using `i3` window manager and `urxvt` terminal with `fish` shell. There might be something blocking it from sending but SeLinux is turned off on the system.

**Comment by kennethpjdyer** [comment]
Similar issue on FreeBSD.  Here's the traceback from the logs:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /1.1/statuses/update.json HTTP/1.1" 400 68
ERROR:root:[{u'message': u'media_ids parameter is invalid.', u'code': 44}]
Traceback (most recent call last):
  File "/home/kbapheus/.local/lib/python2.7/site-packages/turses/meta.py", line 35, in wrapper
    result = func(self, *args, **kwargs)
  File "/home/kbapheus/.local/lib/python2.7/site-packages/turses/api/base.py", line 311, in update
    self._api.update(text)
  File "/home/kbapheus/.local/lib/python2.7/site-packages/turses/api/backends.py", line 296, in update
    self._api.update_status(text)
  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tweepy/binder.py", line 239, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/site-packages/tweepy/binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
TweepError: [{u'message': u'media_ids parameter is invalid.', u'code': 44}]
```
