### ISSUE TITLE
TypeError: decoding str is not supported

### ISSUE THREAD

**Issue by clauseggers** [dialelo/turses#221]
I initially installed `turses` via `pip install turses --user` and it worked a few times. Then it stopped working, instead giving me a segmentation fault. Then I installed again it via `pip` in a `virtualenv` to get all the dependencies to the exact right version, but then I got the below error:
```
Traceback (most recent call last):
  File "/usr/home/claus/.local/bin/turses", line 11, in <module>
    sys.exit(main())
  File "/usr/home/claus/.local/virtualenv/turses/env/lib/python3.5/site-packages/turses/cli.py", line 146, in main
    configuration.load()
  File "/usr/home/claus/.local/virtualenv/turses/env/lib/python3.5/site-packages/turses/config.py", line 504, in load
    self._init_config()
  File "/usr/home/claus/.local/virtualenv/turses/env/lib/python3.5/site-packages/turses/config.py", line 513, in _init_config
    self.parse_config_file(self.config_file)
  File "/usr/home/claus/.local/virtualenv/turses/env/lib/python3.5/site-packages/turses/config.py", line 716, in parse_config_file
    self._parse_styles(conf)
  File "/usr/home/claus/.local/virtualenv/turses/env/lib/python3.5/site-packages/turses/config.py", line 760, in _parse_styles
    conf.get(SECTION_STYLES, style), 'utf-8')
TypeError: decoding str is not supported
```
I’m running it on TrueOS (BSD).

**Comment by Chaz6** [comment]
I have the same issue too after installing turses today, on CentOS 7.3.
